export enum SCREENS {
  Main = "Main",
  HomeScreen = "HomeScreen",
  PortfolioStack = "PortfolioStack",
  ReactNativePortfolio = "ReactNativePortfolio",
  ReactPortfolio = "ReactPortfolio",
  BackendPortfolio = "BackendPortfolio",
  InterestsStack = "InterestsStack",
  SettingsStack = "SettingsStack",
  BooksScreen = "BooksScreen",
  SettingsScreen = "SettingsScreen",
  BookSuggestionModal = "BookSuggestionModal",
  WebviewModal = "WebviewModal",
  ArticlesScreen = "ArticlesScreen",
  ContactModal = "ContactModal",
}
