fragment UploadSuccess on SuccessPayload {
  successMessage
}

fragment BookFields on BookPayload {
  author
  bookUrl
  classification
  id
  synopsis
  title
}

fragment ProjectFields on PortfolioPayload {
  buttonOneLink
  buttonOptionOne
  buttonOptionTwo
  buttonTwoLink
  cardBodyText
  headerBody
  headerFooter
  headerTitle
  id
}

fragment ArticleFields on ArticlePayload {
  title
  publisher
  articleUrl
  excerpt
  id
}
