query GetBooks($queryType: String!) {
  getBooks(data: $queryType) {
    ...BookFields
  }
}

query GetProjects($queryType: String!) {
  getProjects(data: $queryType) {
    ...ProjectFields
  }
}

query GetArticles($queryType: String!) {
  getArticles(data: $queryType) {
    ...ArticleFields
  }
}
